#!/bin/sh -ex

DB_NAME=mambo
DB_USER=mambo
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/mambo

# unpack and set permissions
mkdir -p $WEBROOT
tar -zxf $SRC/Mambo*.tar.gz -C $WEBROOT
rm $SRC/Mambo*.tar.gz
chown -R root:root $WEBROOT
find $WEBROOT -type f -print0 | xargs -0 chmod 644
find $WEBROOT -type d -print0 | xargs -0 chmod 755
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/media
chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/modules
chown -R www-data:www-data $WEBROOT/mambots
chown -R www-data:www-data $WEBROOT/language
chown -R www-data:www-data $WEBROOT/templates
chown -R www-data:www-data $WEBROOT/components
chown -R www-data:www-data $WEBROOT/uploadfiles
chown -R www-data:www-data $WEBROOT/administrator
chown www-data:www-data $WEBROOT/installation/langconfig.php

# apply patches to support php 5.3
PATCHES=$SRC/patches
patch $WEBROOT/includes/database.php $PATCHES/php53_database.diff
patch $WEBROOT/includes/Cache/Lite/Function.php $PATCHES/php53_cache.diff
rm -rf $PATCHES

# configure apache
a2dissite default
a2ensite mambo
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# setup blank configuration for installation
CONF=$WEBROOT/configuration.php
touch $CONF
chown www-data:www-data $CONF
chmod 640 $CONF

# curl based install
URL="http://127.0.0.1/installation"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

C_WWWROOT=$(echo $WEBROOT/ | sed "s|\/|%2F|g")
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
NEXT="next=Next+%3E%3E"
DBCONF="DBhostname=localhost&DBuserName=$DB_USER&DBpassword=$DB_PASS&DBverifypassword=$DB_PASS&DBname=$DB_NAME&DBPrefix="

$CURL "${URL}/install1.php" --data "$NEXT"
$CURL "${URL}/install2.php" --data "$NEXT&$DBCONF&DBSample=1"
$CURL "${URL}/install3.php" --data "$NEXT&$DBCONF&DBcreated=1&sitename=TurnKey+Mambo"
$CURL "${URL}/install4.php" --data "$NEXT&$DBCONF&DBcreated=1&sitename=TurnKey+Mambo& siteUrl=http%3A%2F%2F127.0.0.1&absolutePath=$C_WEBROOT&adminEmail=$EMAIL&adminPassword=$ADMIN_PASS&filePermsMode=0&filePermsUserRead=1&filePermsUserWrite=1&filePermsGroupRead=1&filePermsWorldRead=1&dirPermsMode=0&dirPermsUserRead=1&dirPermsUserWrite=1&dirPermsUserSearch=1&dirPermsGroupRead=1&dirPermsGroupSearch=1&dirPermsWorldRead=1&dirPermsWorldSearch=1"

rm -rf $WEBROOT/installation
rm -f /tmp/cookie

# blank out hardcoded site url, set mailer to smtp and enable sef
CONF=$WEBROOT/configuration.php
sed -i "s|mosConfig_live_site =.*|mosConfig_live_site = '';|" $CONF
sed -i "s|mosConfig_mailer =.*|mosConfig_mailer = 'smtp';|" $CONF
sed -i "s|mosConfig_sef =.*|mosConfig_sef = '1';|" $CONF
mv $WEBROOT/htaccess.txt $WEBROOT/.htaccess

# tweak footer
cat >>$WEBROOT/includes/footer.php<<EOF
<div id="turnkey-credit" style="text-align:center;padding-top:20px;"><a href="http://www.turnkeylinux.org/mambo">Mambo Appliance</a> - Powered by <a href="http://www.turnkeylinux.org">TurnKey Linux</a></div>
EOF

# convenience and cleanup
ln -s $WEBROOT/administrator $WEBROOT/admin
rm -f $WEBROOT/htaccess.txt.45x
rm -f $WEBROOT/configuration.sample.php

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

