#!/bin/sh -ex

DB_NAME=mambo
DB_USER=mambo
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/mambo

# unpack and set permissions
mkdir -p $WEBROOT
tar -zxf $SRC/Mambo*.tar.gz -C $WEBROOT
rm $SRC/Mambo*.tar.gz
chown -R root:root $WEBROOT
find $WEBROOT -type f -print0 | xargs -0 chmod 644
find $WEBROOT -type d -print0 | xargs -0 chmod 755
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/media
chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/modules
chown -R www-data:www-data $WEBROOT/mambots
chown -R www-data:www-data $WEBROOT/language
chown -R www-data:www-data $WEBROOT/templates
chown -R www-data:www-data $WEBROOT/components
chown -R www-data:www-data $WEBROOT/uploadfiles
chown -R www-data:www-data $WEBROOT/administrator
chown www-data:www-data $WEBROOT/installation/langconfig.php

# apply patches to support php 5.3
PATCHES=$SRC/patches
patch $WEBROOT/includes/database.php $PATCHES/php53_database.diff
patch $WEBROOT/includes/Cache/Lite/Function.php $PATCHES/php53_cache.diff
rm -rf $PATCHES

# configure apache
a2dissite default
a2ensite mambo
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

