#!/bin/bash -e
# regenerate mambo secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/mambo/configuration.php

SECRET=$(mcookie | cut --bytes 1-16)
sed -i "s|mosConfig_secret =.*|mosConfig_secret = '$SECRET';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|mosConfig_password =.*|mosConfig_password = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=mambo --pass="$PASSWORD"

